#!/usr/bin/env python3
"""Validate re_nilm detectors against reference detection scripts on N customers.

For each technology (PV, AC, HP, Battery, EV), runs both the reference and the
current re_nilm detection logic on the same randomly sampled customers and
reports binary classification agreement. Target: >= 95% agreement per technology.

EV has no reference Python script (original source was a notebook). Sanity
checks are run instead: probability in [0, 1], session counts non-negative.

The reference detection scripts are imported from ``old_files/model/`` and
``old_files/hp_model/``, which are added to sys.path automatically.

Prerequisites:
    - Smart meter parquet files at ``--data-dir``.
    - Weather parquet generated by a prior pipeline run (see ``--weather``).
      The pipeline writes this to the results directory as
      ``weather_<backend>_<start>_<end>.parquet`` — check ``data/processed/out/``
      for the exact filename.
    - Pre-trained model artifacts in ``models/`` (ac_detector_v1.joblib,
      hp_detector_v1.joblib). Run ``train_models.py`` first if missing.

Output:
    CSV report at the path given by ``--output`` (default: validation_report.csv).
    A summary table is also printed to stdout.

Usage:
    python scripts/validate_detectors.py \\
        --data-dir data/re_data/ETHZ_ALL \\
        --weather data/processed/out/weather_meteoswiss_None_None.parquet \\
        --n-customers 50 \\
        --seed 42 \\
        --output validation_report.csv
"""

from __future__ import annotations

import argparse
import logging
import random
import sys
from pathlib import Path
from typing import Dict, List, Optional

import joblib
import numpy as np
import pandas as pd

_REPO = Path(__file__).resolve().parents[1]
_MODEL_DIR = _REPO / "old_files" / "model"
_HP_MODEL_DIR = _REPO / "old_files" / "hp_model"
for _p in [str(_REPO), str(_MODEL_DIR), str(_HP_MODEL_DIR)]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

from re_nilm.pipeline.customer_index import build_customer_file_index, load_customer_from_index
from re_nilm.detectors.pv import PVDetector
from re_nilm.detectors.ac import ACDetector
from re_nilm.detectors.heat_pump import HeatPumpDetector
from re_nilm.detectors.battery import BatteryDetector
from re_nilm.detectors.ev import EVDetector

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Weather helpers
# ---------------------------------------------------------------------------

def _load_weather(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Weather cache not found: {path}\nRun the pipeline once first to generate it.")
    df = pd.read_parquet(path)
    for col in ("dt_utc", "t_2m_C", "global_rad_W"):
        if col not in df.columns:
            raise ValueError(f"Weather parquet missing column '{col}'")
    df["dt_utc"] = pd.to_datetime(df["dt_utc"]).astype("datetime64[us]")
    return df.sort_values("dt_utc").reset_index(drop=True)


def _weather_indexed(weather_df: pd.DataFrame) -> pd.DataFrame:
    """Return weather indexed by timestamp (used by old PV + Battery code)."""
    w = weather_df.rename(columns={"dt_utc": "timestamp"}).copy()
    w["timestamp"] = pd.to_datetime(w["timestamp"])
    return w.set_index("timestamp").sort_index()


# ---------------------------------------------------------------------------
# OLD detectors
# ---------------------------------------------------------------------------

def _old_pv_batch(customers: Dict[str, pd.DataFrame], weather_df: pd.DataFrame) -> Dict[str, dict]:
    """Run old pv_detection batch logic on all loaded customers."""
    from pv_detection import (
        compute_daily_weather,
        build_customer_daily_features,
        compute_pv_indicators,
        classify_pv_customers,
    )

    weather_idx = _weather_indexed(weather_df)

    frames = []
    for cid, df in customers.items():
        d = df.copy()
        d["DT_UTC"] = pd.to_datetime(d["DT_UTC"], errors="coerce").astype("datetime64[us]")
        d["ID"] = cid
        frames.append(d)
    if not frames:
        return {}
    re_data = pd.concat(frames, ignore_index=True)

    # Merge global_rad_W from indexed weather
    re_data = re_data.sort_values("DT_UTC")
    weather_reset = weather_idx[["global_rad_W"]].rename_axis("DT_UTC").reset_index()
    weather_reset["DT_UTC"] = weather_reset["DT_UTC"].astype("datetime64[us]")
    re_data_with_meteo = pd.merge_asof(
        re_data,
        weather_reset,
        on="DT_UTC",
        direction="backward",
        tolerance=pd.Timedelta("1h"),
    )

    daily_weather = compute_daily_weather(weather_idx)
    daily_features = build_customer_daily_features(re_data_with_meteo, daily_weather)

    pv_indicators = compute_pv_indicators(daily_features, re_data_with_meteo)
    if pv_indicators.empty:
        return {}
    pv_classified = classify_pv_customers(pv_indicators)

    results = {}
    for _, row in pv_classified.iterrows():
        cid = str(row["customer_id"])
        results[cid] = {
            "has_pv": bool(row.get("has_pv", False)),
            "has_pv_prob": float(row.get("has_pv_prob", np.nan)),
            "corr_prod_rad": float(row.get("corr_prod_rad", np.nan)),
            "DeltaNet": float(row.get("DeltaNet", np.nan)),
        }
    return results


def _old_ac_batch(customers: Dict[str, pd.DataFrame], weather_df: pd.DataFrame) -> Dict[str, dict]:
    """Run old AC feature extraction + pre-trained model on all customers."""
    from ac_actrainingfunctions import (
        FEATURE_COLS,
        AC_PROB_THRESHOLD,
        tot_curve_is_usable,
        extract_tot_features,
    )

    model_path = _REPO / "models" / "ac_detector_v1.joblib"
    if not model_path.exists():
        log.warning("AC model not found at %s — skipping old AC comparison", model_path)
        return {}
    model = joblib.load(model_path)

    # Build per-customer batch rows in the format the old code expects
    w = weather_df[["dt_utc", "t_2m_C", "global_rad_W"]].copy()
    w["dt_utc"] = pd.to_datetime(w["dt_utc"]).astype("datetime64[us]")
    w = w.rename(columns={"t_2m_C": "temp", "global_rad_W": "glob_rad"})

    results = {}
    for cid, df in customers.items():
        try:
            d = df.copy()
            d["DT_UTC"] = pd.to_datetime(d["DT_UTC"], errors="coerce").astype("datetime64[us]")
            d = d.dropna(subset=["DT_UTC"]).sort_values("DT_UTC")
            d = d.rename(columns={"DT_UTC": "dt_utc"})
            d["id_customer"] = cid
            d["type"] = "TOT"
            d["source"] = "validation"
            d["value_kw_mean"] = pd.to_numeric(d["CONSO_KWH"], errors="coerce") * 4.0
            d = pd.merge_asof(d, w, on="dt_utc", direction="backward", tolerance=pd.Timedelta("1h"))
            tot_df = d[d["type"] == "TOT"].copy()
            usable, _, _ = tot_curve_is_usable(tot_df)
            if not usable:
                continue
            feats = extract_tot_features(tot_df)
            if feats is None:
                continue
            X = pd.DataFrame([feats])[FEATURE_COLS].to_numpy(dtype=float)
            proba = model.predict_proba(X)
            classes = model.named_steps["clf"].classes_
            has_ac_idx = int(np.where(classes == 1)[0][0]) if 1 in classes else 0
            prob_ac = float(proba[0, has_ac_idx])
            results[cid] = {"has_ac": bool(prob_ac >= AC_PROB_THRESHOLD), "prob_ac": prob_ac}
        except Exception as exc:
            log.debug("Old AC failed for %s: %s", cid, exc)
    return results


def _old_hp_batch(customers: Dict[str, pd.DataFrame], weather_df: pd.DataFrame) -> Dict[str, dict]:
    """Run old HP feature extraction + pre-trained model on all customers."""
    from hp_detection_functions import (
        FEATURE_COLS,
        INT_TO_LABEL,
        tot_curve_is_usable,
        extract_tot_features,
    )

    model_path = _REPO / "models" / "hp_detector_v1.joblib"
    if not model_path.exists():
        log.warning("HP model not found at %s — skipping old HP comparison", model_path)
        return {}
    model = joblib.load(model_path)

    w = weather_df[["dt_utc", "t_2m_C", "global_rad_W"]].copy()
    w["dt_utc"] = pd.to_datetime(w["dt_utc"]).astype("datetime64[us]")
    w = w.rename(columns={"t_2m_C": "temp", "global_rad_W": "glob_rad"})

    results = {}
    for cid, df in customers.items():
        try:
            d = df.copy()
            d["DT_UTC"] = pd.to_datetime(d["DT_UTC"], errors="coerce").astype("datetime64[us]")
            d = d.dropna(subset=["DT_UTC"]).sort_values("DT_UTC")
            d = d.rename(columns={"DT_UTC": "dt_utc"})
            d["id_customer"] = cid
            d["type"] = "TOT"
            d["source"] = "validation"
            d["value_kw_mean"] = pd.to_numeric(d["CONSO_KWH"], errors="coerce") * 4.0
            d = pd.merge_asof(d, w, on="dt_utc", direction="backward", tolerance=pd.Timedelta("1h"))
            tot_df = d[d["type"] == "TOT"].copy()
            usable, _, _ = tot_curve_is_usable(tot_df)
            if not usable:
                continue
            feats = extract_tot_features(tot_df)
            if feats is None:
                continue
            X = pd.DataFrame([feats])[FEATURE_COLS].to_numpy(dtype=float)
            pred = int(model.predict(X)[0])
            pred_name = INT_TO_LABEL.get(pred, "no_hp")
            proba = model.predict_proba(X)
            classes = model.named_steps["clf"].classes_
            hp_probs = {}
            for cls_id, cls_name in INT_TO_LABEL.items():
                if cls_id in classes:
                    idx = int(np.where(classes == cls_id)[0][0])
                    hp_probs[cls_name] = float(proba[0, idx])
                else:
                    hp_probs[cls_name] = 0.0
            prob_hp = hp_probs.get("winter_hp", 0.0) + hp_probs.get("summer_hp", 0.0)
            results[cid] = {
                "has_hp": pred_name != "no_hp",
                "hp_type": pred_name,
                "prob_hp": prob_hp,
            }
        except Exception as exc:
            log.debug("Old HP failed for %s: %s", cid, exc)
    return results


def _old_battery_per_customer(
    customers: Dict[str, pd.DataFrame],
    weather_df: pd.DataFrame,
    pv_results: Dict[str, dict],
) -> Dict[str, dict]:
    """Run old analyze_battery_residential_v7 per customer."""
    try:
        from battery_detection import analyze_battery_residential_v7
    except ImportError:
        log.warning("battery_detection not importable — skipping old battery comparison")
        return {}

    weather_idx = _weather_indexed(weather_df)
    results = {}
    for cid, df in customers.items():
        pv = pv_results.get(cid, {})
        if not pv.get("has_pv", False):
            results[cid] = {"has_battery": False, "prob_battery": 0.0, "status": "skipped_no_pv"}
            continue
        try:
            d = df.copy()
            d["DT_UTC"] = pd.to_datetime(d["DT_UTC"], errors="coerce")
            d = d.dropna(subset=["DT_UTC"]).set_index("DT_UTC").sort_index()
            pv_row = {
                "pv_capacity_kwp": pv.get("pv_capacity_kwp", 0.0),
                "has_pv": True,
                "has_pv_prob": pv.get("has_pv_prob", np.nan),
            }
            res = analyze_battery_residential_v7(d, weather_idx, pv_row)
            prob_raw = float(res.get("battery_prob", 0.0))
            prob = prob_raw / 100.0 if prob_raw > 1.0 else prob_raw
            results[cid] = {
                "has_battery": prob >= 0.5,
                "prob_battery": prob,
                "status": res.get("status", "ok"),
            }
        except Exception as exc:
            log.debug("Old battery failed for %s: %s", cid, exc)
    return results


# ---------------------------------------------------------------------------
# NEW detectors
# ---------------------------------------------------------------------------

def _run_new_detectors(
    customers: Dict[str, pd.DataFrame],
    weather_df: pd.DataFrame,
    models_dir: Path,
) -> Dict[str, Dict[str, dict]]:
    """Run all new detectors on each customer. Returns {technology: {cid: result}}."""
    pv_det = PVDetector()
    ev_det = EVDetector()

    ac_model_path = models_dir / "ac_detector_v1.joblib"
    hp_model_path = models_dir / "hp_detector_v1.joblib"
    ac_det = ACDetector.load(ac_model_path) if ac_model_path.exists() else None
    hp_det = HeatPumpDetector.load(hp_model_path) if hp_model_path.exists() else None
    batt_det = BatteryDetector()

    new_pv, new_ac, new_hp, new_batt, new_ev = {}, {}, {}, {}, {}

    for cid, df in customers.items():
        r_pv = pv_det.predict_customer(df, weather_df)
        if r_pv:
            new_pv[cid] = r_pv

        if ac_det:
            try:
                r_ac = ac_det.predict_customer(df, weather_df)
                if r_ac:
                    new_ac[cid] = r_ac
            except Exception as exc:
                log.debug("New AC failed for %s: %s", cid, exc)

        if hp_det:
            try:
                r_hp = hp_det.predict_customer(df, weather_df)
                if r_hp:
                    new_hp[cid] = r_hp
            except Exception as exc:
                log.debug("New HP failed for %s: %s", cid, exc)

        r_batt = batt_det.predict_customer(df, weather_df, pv_result=new_pv.get(cid))
        if r_batt:
            new_batt[cid] = r_batt

        r_ev = ev_det.predict_customer(df, weather_df)
        if r_ev:
            new_ev[cid] = r_ev

    return {
        "pv": new_pv,
        "ac": new_ac,
        "hp": new_hp,
        "battery": new_batt,
        "ev": new_ev,
    }


# ---------------------------------------------------------------------------
# Comparison helpers
# ---------------------------------------------------------------------------

def _compare_binary(
    old: Dict[str, dict],
    new: Dict[str, dict],
    technology: str,
    old_flag: str,
    new_flag: str,
    old_prob: Optional[str],
    new_prob: Optional[str],
) -> pd.DataFrame:
    common = set(old) & set(new)
    if not common:
        log.warning("[%s] No overlapping customers between old and new — skipping", technology)
        return pd.DataFrame()
    rows = []
    for cid in sorted(common):
        o, n = old[cid], new[cid]
        old_val = bool(o.get(old_flag, False))
        new_val = bool(n.get(new_flag, False))
        row = {
            "technology": technology,
            "customer_id": cid,
            "old_pred": old_val,
            "new_pred": new_val,
            "agreement": old_val == new_val,
        }
        if old_prob:
            row["old_prob"] = round(float(o.get(old_prob, np.nan)), 4)
        if new_prob:
            row["new_prob"] = round(float(n.get(new_prob, np.nan)), 4)
        if old_prob and new_prob:
            row["prob_delta"] = round(row["new_prob"] - row["old_prob"], 4)
        rows.append(row)
    return pd.DataFrame(rows)


def _sanity_ev(new_ev: Dict[str, dict]) -> pd.DataFrame:
    rows = []
    for cid, r in new_ev.items():
        prob = float(r.get("prob_ev", np.nan))
        sessions = int(r.get("ev_total_sessions", -1))
        yearly = float(r.get("ev_yearly_mwh", np.nan))
        sanity_ok = (
            0.0 <= prob <= 1.0
            and sessions >= 0
            and yearly >= 0.0
        )
        rows.append({
            "technology": "ev",
            "customer_id": cid,
            "new_pred": bool(r.get("has_ev", False)),
            "prob_ev": round(prob, 4),
            "ev_total_sessions": sessions,
            "ev_yearly_mwh": round(yearly, 2),
            "sanity_ok": sanity_ok,
        })
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------

def _print_summary(report: pd.DataFrame) -> None:
    print("\n" + "=" * 60)
    print("VALIDATION SUMMARY")
    print("=" * 60)

    for tech, grp in report.groupby("technology"):
        if "agreement" in grp.columns and grp["agreement"].notna().any():
            n = len(grp)
            n_agree = int(grp["agreement"].sum())
            pct = 100.0 * n_agree / n if n else 0.0
            status = "✓ PASS" if pct >= 95 else "✗ FAIL"
            print(f"  {tech:10s}  {n_agree:3d}/{n:3d} agree  ({pct:.1f}%)  {status}")
            if "prob_delta" in grp.columns:
                med_delta = grp["prob_delta"].abs().median()
                print(f"             median |prob_delta| = {med_delta:.4f}")
        elif tech == "ev" and "sanity_ok" in grp.columns:
            n = len(grp)
            n_ok = int(grp["sanity_ok"].sum())
            pct = 100.0 * n_ok / n if n else 0.0
            status = "✓ PASS" if pct == 100 else "✗ FAIL"
            print(f"  {'ev':10s}  {n_ok:3d}/{n:3d} sane   ({pct:.1f}%)  {status}  [sanity only]")

    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Validate re_nilm detectors vs legacy scripts")
    parser.add_argument("--data-dir", required=True, type=Path, help="Directory with RE parquet files")
    parser.add_argument("--weather", required=True, type=Path, help="Path to weather_cache.parquet")
    parser.add_argument("--n-customers", type=int, default=50, help="Number of customers to sample")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for customer sampling")
    parser.add_argument("--output", type=Path, default=Path("validation_report.csv"))
    parser.add_argument("--models-dir", type=Path, default=Path("models"))
    args = parser.parse_args()

    # Resolve paths relative to repo root when run from any directory
    data_dir = (args.data_dir if args.data_dir.is_absolute() else _REPO / args.data_dir)
    weather_path = (args.weather if args.weather.is_absolute() else _REPO / args.weather)
    models_dir = (args.models_dir if args.models_dir.is_absolute() else _REPO / args.models_dir)

    log.info("Loading weather from %s", weather_path)
    weather_df = _load_weather(weather_path)

    log.info("Building customer index from %s", data_dir)
    index = build_customer_file_index(data_dir)
    all_ids = sorted(index.keys())
    if not all_ids:
        raise RuntimeError(f"No customers found in {data_dir}")

    rng = random.Random(args.seed)
    sample_ids = rng.sample(all_ids, min(args.n_customers, len(all_ids)))
    log.info("Sampled %d customers (seed=%d)", len(sample_ids), args.seed)

    log.info("Loading customer data...")
    customers: Dict[str, pd.DataFrame] = {}
    for cid in sample_ids:
        df = load_customer_from_index(cid, index)
        if not df.empty:
            customers[cid] = df
    log.info("Loaded %d non-empty customers", len(customers))

    # --- New detectors ---
    log.info("Running new re_nilm detectors...")
    new_results = _run_new_detectors(customers, weather_df, models_dir)

    # --- Old detectors ---
    log.info("Running old PV detection (batch)...")
    old_pv = _old_pv_batch(customers, weather_df)

    log.info("Running old AC detection (per customer)...")
    old_ac = _old_ac_batch(customers, weather_df)

    log.info("Running old HP detection (per customer)...")
    old_hp = _old_hp_batch(customers, weather_df)

    log.info("Running old Battery detection (per customer)...")
    old_batt = _old_battery_per_customer(customers, weather_df, new_results["pv"])

    # --- Comparisons ---
    frames: List[pd.DataFrame] = []

    df_pv = _compare_binary(old_pv, new_results["pv"], "pv", "has_pv", "has_pv", "has_pv_prob", "prob_pv")
    frames.append(df_pv)

    if old_ac and new_results["ac"]:
        df_ac = _compare_binary(old_ac, new_results["ac"], "ac", "has_ac", "has_ac", "prob_ac", "prob_ac")
        frames.append(df_ac)
    else:
        log.warning("AC comparison skipped (old=%d new=%d customers)", len(old_ac), len(new_results["ac"]))

    if old_hp and new_results["hp"]:
        df_hp = _compare_binary(old_hp, new_results["hp"], "hp", "has_hp", "has_hp", "prob_hp", "prob_hp")
        frames.append(df_hp)
    else:
        log.warning("HP comparison skipped (old=%d new=%d customers)", len(old_hp), len(new_results["hp"]))

    if old_batt and new_results["battery"]:
        df_batt = _compare_binary(old_batt, new_results["battery"], "battery", "has_battery", "has_battery", "prob_battery", "prob_battery")
        frames.append(df_batt)
    else:
        log.warning("Battery comparison skipped")

    if new_results["ev"]:
        df_ev = _sanity_ev(new_results["ev"])
        frames.append(df_ev)

    if not frames:
        log.error("No comparison data generated — check data paths and model files")
        sys.exit(1)

    report = pd.concat(frames, ignore_index=True)
    output_path = (args.output if args.output.is_absolute() else _REPO / args.output)
    report.to_csv(output_path, index=False)
    log.info("Report saved → %s", output_path)

    _print_summary(report)


if __name__ == "__main__":
    main()
